config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  namespace :admin do
    get 'questions/index'
  end

  resources :questions do
    resources :answers

    resources :likes, only: [:create, :destroy]

    resources :favourites, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  resources :favourites, only: [:index]

  get "/about" => "about#index", as: :about

  get "/contact"  => "contact#index", as: :contact
  post "/contact" => "contact#create"

  get "/welcome/:name" => "welcome#show", as: :welcome

  get "/welcome/hello" => "welcome#hello", as: :hello_welcome

  namespace :admin do
    get "/questions" => "questions#index"
  end

  root "contact#index"

end

app/models/question.rb
class Question < ActiveRecord::Base


  # This assumes you have a model called "answer"
  # it also assumes that the model has a field called
  # question_id which is an integer
  # dependent is an option that takes an argument:
  # :destroy: will destroy all the answers with this
  #           records id (in question_id)
  # :nullify: will make the question_id field
  #           nil for associated answers
  has_many :answers, dependent: :destroy

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :favourites, dependent: :destroy
  has_many :favourited_users, through: :favourites, source: :user

  has_many :votes, dependent: :destroy
  has_many :voted_users, through: :votes, source: :user


  belongs_to :user

  validates :title, presence:   {message: "must be provided."}, 
                    uniqueness: {case_sensitive: false},
                    length:     {minimum: 10}

  validates :body, presence: true

  validates :view_count, numericality: {greater_than_or_equal_to: 0}

  validate :stop_words

  # the set_defaults method will be called after a new object
  # is initialized, for instance, after calling:
  # q = Question.new
  after_initialize :set_defaults

  scope :recent, lambda { order("updated_at DESC") }
  # this is the same as doing
  # def self.recent
  #   order("updated_at DESC")
  # end

  scope :recent_ten, lambda { recent.limit(10) }

  # taking an argument for scope
  scope :most_recent, lambda { |n| recent.limit(n)  }
  # this is the same as doing
  # def most_recent(n)
  #   recent.limit(n)
  # end

  # scope that gives back the questions created in the last three days
  scope :last_three_days, lambda { where("created_at >= ?", 3.days.ago) }

  # scope that gives back the questions created in the last ten days
  # using a range instead of using >=
  scope :last_ten_days, lambda { where(created_at: 
                                  (Time.now - 10.days)..(Time.now)) }

  # Write a scope or a method that gives the questions created
  # in the last X days. callit: days_ago
  def self.days_ago(n)
    where("created_at >= ?", n.days.ago)
  end


  # this will call the capitalize_title method
  # right before saving the record
  before_save :capitalize_title

  # If you have an email you can validate the format of that emal
  # using regular expressions as in:
  # validates :email, format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  # this validates the the title/body combintation is unqiue
  # This means that body doesn't have to be unique by itself
  # same for title. But the combination has to be unique
  #  validates :body, uniqueness: {scope: :title}

  def self.search(search_term)
    Question.where("title ILIKE ? OR body ILIKE  ?", 
                        "%#{search_term}%", "%#{search_term}%")
  end

  def increment_view_count
    # You normally need to use self. if you're setting an attribute
    # if you reading an attribute or calling a method then the self.
    # is not needed.
    # self.view_count += 1
    # save
    increment!(:view_count)
  end

  def like_for(user)
    likes.find_by_user_id(user.id) if user
  end

  def favourite_for(user)
    favourites.find_by_user_id(user.id) if user
  end

  def vote_for(user)
    votes.find_by_user_id(user.id) if user
  end

  def votes_count
    votes.up.count - votes.down.count
  end

  private

  def set_defaults
    self.view_count ||= 0
  end

  def capitalize_title
    self.title.capitalize!
  end

  def stop_words
    if title.present? && title.include?("monkey")
      # this adds error to the errors object for this activerecord
      # object. Errors are added to a specific attribute. In this case
      # the attribute is :title. If you don't want to attach the error
      # to a specific attribute. Then use :base
      errors.add(:base, "Please don't put monkey in title")
    end
  end

end


# this is fine
# def search(user_input) 
#   Question.where("title ILIKE ?", "%#{user_input}%")
# end

# Don't do this - Possible SQL Injection Exploit
# def search(user_input) 
#   Question.where("title ILIKE '%#{user_input}%'")
# end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  QUESTIONS_PER_PAGE = 20

  # this means that before the actions specific in the :only array
  # the method "find_quesiton" will be called
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  # this will be invoied with 
  # GET        request
  # /questions URL
  def index
    @questions = Question.page(params[:page]).per(QUESTIONS_PER_PAGE)
    # if params[:search]
    #   @questions = Question.search(params[:search])
    # else
    #   @questions = Question.all
    # end
  end

  def new
    # instantiating a new question (model) object
    # this will be useful to easily generate the form
    # the will be used to create the question
    @question = Question.new
  end

  # This will be called when the URL is:
  # METHOD: Post
  # URL   : /questions
  def create
    # params[:question] looks like:
    # {"title"=>"another question", "body"=>"asd fasf asdf asdf asdf "}
    
    # intantiating a new question object with the parameters
    # we got from the user
    # using current_user.questions.new instead of Question.new
    # makes the instantiated question associated with the current_user
    @question = current_user.questions.new(question_params)
    
    # Saving the question record
    if @question.save
      # Redirect to the show page for the created question
      flash[:notice] = "Question Created Successfully!"
      # redirect_to question_path(id: @question.id)
      redirect_to question_path(@question)
    else
      # Show the form again with errors displayed at top
      # You can also do:
      # render "questions/new"
      # but it's redudent as the questions/ is implied by convention
      # with Rails
      render :new
    end
  end

  # This will be called when the URL is:
  # METHOD: GET
  # URL   : /questions/:id
  # for instance: /questions/5
  def show
    # this will print part of the Rails logs
    # there are different levels of Rails logs:
    # info / debug / error
    Rails.logger.info ">>>>>>>>>>>>>>>> #{@question.title}"

    @like      = @question.like_for(current_user)      if user_signed_in?
    @favourite = @question.favourite_for(current_user) if user_signed_in?
    @vote      = @question.vote_for(current_user)      if user_signed_in?
    @question.increment_view_count
    # Instantiating an empty answer object to be used
    # with the form that creates an answer on the 
    # the question show page
    @answer = Answer.new
    # You can put byebug anywhere in your code and the execution
    # will stop and you will have the option to insepct and play
    # with you code in the Rails console
    # byebug

    # this will open up Pry in Rails console
    # similar to byebug with all the features
    # from Pry
    # binding.pry
    
  end

  # This will be called when the URL is:
  # METHOD: GET
  # URL   : /questions/:id/edit
  # for instance: /questions/5/edit
  def edit
  end

  # This will be called when the URL is:
  # METHOD: PATCH (or PUT)
  # URL   : /questions/:id
  # for instance: /questions/5
  def update
    # update method in ActiveRecord takes a hash like
    # {title: "abc", body: "asdfasdf"}
    if @question.update(question_params)
      # redirect_to question_path(@question)
      redirect_to @question, notice: "Question updated successfully!"
    else
      flash[:alert] = "Please correct errors below"
      render :edit
    end
  end

  # This will be called when the URL is:
  # METHOD: DELETE
  # URL   : /questions/:id
  # for instance: /questions/5
  def destroy
    @question.destroy
    redirect_to questions_path, notice: "Question deleted successfully!"
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    # This uses a feature called "Strong Parameters" introduced
    # to Rails by version 4. It makes you be explicit about
    # the parameters you want the user to be able to create/edit.
    # in the case below I'm requireing that there is a key
    # called question and inside I'm allowing only :title and :body
    # parameters to be created 
    params.require(:question).permit(:title, :body, {category_ids: []})
  end

end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%# if @question has validation errors it will be included %>
<%# part of the errors objects included in it %>
<% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%# form_for is a view help from Rails that helps %>
<%# generate a forms in Rails application. %>
<%# It takes multiple parameters. The first parameter %>
<%# best be an ActiveRecord object. %>
<%# From that the form_for will figure out the following: %>
<%# ACTION: depending on the type of the object. For instance  if the object type is "Question" the action will be "/questions" (questions_path) %>
<%# METHOD: if the passed ActiveRecord object (@question) is persisted (saved to database) in the database it will use PATCH. If it's not persisted it will use POST %>
<%= form_for @question do |f| %>
  <%= f.label :idea %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :notes %>
  <%= f.text_area :body %>
  <br>
  <%# collection_check_boxes is a helper that comes with Rails to build %>
  <%# a collection of checkboxes. It expects four paramaters. The first one%>
  <%# is the "name" attribute to be sent to the server. The second parameter %>
  <%# should be the collection of objects. Usually ActiveRecord objects. %>
  <%# The third parameter is the value to be sent to the server.%>
  <%# The fourth paramter is the method to be used for display as label %>
  <%# for the checkbox. %>
  <%# http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-collection_check_boxes %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  <%= f.submit "Submit Idea!"  %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Questions</h1>

<%# This will look for a partial named _form.html.erb %>
<%# within the same folder of this file %>
<%= render "form" %>

app/views/questions/index.html.haml
%h1 Questions#index
%p Find me in app/views/questions/index.html.erb
- @questions.each do |question|
  =# link_to question.title, question_path(question)
  = link_to question.title, question
  %hr

= paginate @questions

app/views/questions/new.html.erb
<h1>Share A New Idea!</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %>
<p> View Count: <%= @question.view_count %></p>
<% if @question.user.present? %>
  <p>Created By: <%= @question.user.name_display %><p>
<% end %>

<p>Likes: <%= @question.likes.count %></p>
<% if @like %>
  <%= link_to fa_icon("thumbs-up 3x"), question_like_path(@question, @like), method: :delete %>
<% else %>
  <%= link_to fa_icon("thumbs-o-up 3x"), question_likes_path(@question), method: :post %>
<% end %>

<p>Favourited: <%= @question.favourites.count %> times</p>
<% if @favourite %>
  <%= link_to fa_icon("star 3x"), question_favourite_path(@question, @favourite), method: :delete %>
<% else %>
  <%= link_to fa_icon("star-o 3x"), question_favourites_path(@question), method: :post %>
<% end %>

<br>

Votes: <%= @question.votes_count %>
<% if @vote %>
  <% if @vote.is_up? %>
    <%= link_to fa_icon("caret-up 5x"), question_vote_path(@question, @vote), method: :delete %>
    <br>
    <%= link_to fa_icon("chevron-down 3x"), question_vote_path(@question, @vote, {vote: {is_up: false}}), method: :patch %>
  <% else %>
    <%= link_to fa_icon("chevron-up 3x"), question_vote_path(@question, @vote, {vote: {is_up: true}}), method: :patch %>
    <br>
    <%= link_to fa_icon("caret-down 5x"), question_vote_path(@question, @vote), method: :delete %>
  <% end %>
<% else %>
  <%= link_to fa_icon("chevron-up 3x"), question_votes_path(@question, {vote: {is_up: true}}), method: :post %>
  <br>
  <%= link_to fa_icon("chevron-down 3x"), question_votes_path(@question, {vote: {is_up: false}}), method: :post %>
<% end %>



<%= link_to "Edit", edit_question_path(@question) %>
<%= button_to "Delete", question_path(@question), method: :delete, data: {confirm: "Are you sure?"} %>
<hr>
<h2>Submit an answer</h2>
<% if @answer.errors.any? %>
  <ul>
    <% @answer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%# doing form_for @answer will submit to answers_path %>
<%# by default which is not what we want. %>
<%# That's why we must provide the url option %>
<%= form_for @answer, url: question_answers_path(@question) do |f| %>
  <%# this is a shortcut for the above: %>
  <%#= form_for [@question, @answer] do |f| %>
  <%= f.text_area :body, placeholder: "Put your answer here" %>
  <br>
  <%= f.submit "Submit Answer" %> 
<% end %>

<h2>Answers</h2>
<% @question.answers.each do |ans| %>
  <p>
    <%= ans.body %>
    <%= button_to "Delete", question_answer_path(@question, ans), method: :delete, data: {confirm: "Are you sure?"} %>
    <% if ans.user.present? %>
      <p>Answered by: <%= ans.user.name_display %></p>
    <% end %>
  </p>
  <hr>
<% end %>