config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  namespace :admin do
    get 'questions/index'
  end

  resources :questions do
    resources :answers

    resources :likes, only: [:create, :destroy]

    resources :favourites, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  resources :favourites, only: [:index]

  get "/about" => "about#index", as: :about

  get "/contact"  => "contact#index", as: :contact
  post "/contact" => "contact#create"

  get "/welcome/:name" => "welcome#show", as: :welcome

  get "/welcome/hello" => "welcome#hello", as: :hello_welcome

  namespace :admin do
    get "/questions" => "questions#index"
  end

  root "contact#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Idea Generator!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p align="left"> 
  <%= link_to "Home", root_path %>
  |   
  <%= link_to "All Outstanding Ideas", questions_path %>
  |
  <%= link_to "New Idea?", new_question_path %>
  |
</p>

  <p align="right">
    <% if user_signed_in? %>
      <%# current user is a method from Devise that gives you the user %>
      <%# object for the currently logged in user %>
      Welcome <%= current_user.name_display %>,
      <%= link_to "Favourites", favourites_path %> | 
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log In", new_user_session_path %> |
      <%= link_to "Register", new_user_registration_path %>
    <% end %>
  </p>
    <hr>
  <%= flash[:notice] || flash[:alert] %>
  <hr>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'external', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= link_to "Home", root_path %>
|   
<%= link_to("About", about_path, class: "header-link") %>
| 
<%= link_to "Contact", contact_url %>
<hr>

<%= yield %>

</body>
</html>